# .goreleaser.yaml
version: 2

project_name: keystone

before:
  hooks:
    - go mod tidy

builds:
  - id: keystone
    main: ./cmd/keystone
    binary: keystone
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/carlosprados/keystone/internal/version.Version={{.Version}} -X github.com/carlosprados/keystone/internal/version.Commit={{.Commit}}

  - id: keystonectl
    main: ./cmd/keystonectl
    binary: keystonectl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/carlosprados/keystone/internal/version.Version={{.Version}} -X github.com/carlosprados/keystone/internal/version.Commit={{.Commit}}

  - id: keystoneserver
    main: ./cmd/keystoneserver
    binary: keystoneserver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/carlosprados/keystone/internal/version.Version={{.Version}} -X github.com/carlosprados/keystone/internal/version.Commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: carlosprados
    name: keystone
