package cli

import (
	"bytes"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// The point of the Cobra rewrite is that the tool explains itself. That is a
// promise a test can keep: every command must say what it is for, carry a
// runnable example, and belong to a group so it appears in the help.
func TestEveryCommandDocumentsItself(t *testing.T) {
	root := NewRootCommand()

	for _, cmd := range root.Commands() {
		// help and completion are generated by Cobra; their text is not ours.
		if cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		t.Run(cmd.Name(), func(t *testing.T) {
			if strings.TrimSpace(cmd.Short) == "" {
				t.Error("no Short description: it would be a blank line in `keystonectl help`")
			}
			if strings.TrimSpace(cmd.Long) == "" {
				t.Error("no Long description: `keystonectl help " + cmd.Name() + "` would explain nothing")
			}
			if !strings.Contains(cmd.Example, "keystonectl "+cmd.Name()) {
				t.Errorf("Example does not show `keystonectl %s` being run: %q", cmd.Name(), cmd.Example)
			}
			if cmd.GroupID == "" {
				t.Error("no GroupID: the command would be filed under 'Additional Commands'")
			}
			if cmd.Args == nil {
				t.Error("no Args validator: wrong argument counts would reach the agent")
			}
		})
	}
}

// A command that talks to the agent should name the endpoint it uses, so both a
// human and a machine can map the CLI onto the API by reading --help.
func TestCommandsNameTheEndpointTheyCall(t *testing.T) {
	local := map[string]bool{"version": true, "sha256": true, "help": true, "completion": true}

	for _, cmd := range NewRootCommand().Commands() {
		if local[cmd.Name()] {
			continue
		}
		if !strings.Contains(cmd.Long, "Calls ") {
			t.Errorf("%s: Long does not name the endpoint it calls", cmd.Name())
		}
	}
}

func TestHelpListsEveryGroup(t *testing.T) {
	root := NewRootCommand()
	var out bytes.Buffer
	root.SetOut(&out)
	root.SetErr(&out)
	root.SetArgs([]string{"--help"})
	if err := root.Execute(); err != nil {
		t.Fatalf("--help: %v", err)
	}

	help := out.String()
	for _, want := range []string{"Plan:", "Components:", "Recipes:", "Agent:", "Local tools:"} {
		if !strings.Contains(help, want) {
			t.Errorf("root help is missing the %q group\n%s", want, help)
		}
	}
	// The connection model is the one thing a newcomer cannot guess.
	for _, want := range []string{"KEYSTONE_ADDR", "KEYSTONE_SSH", "--ssh"} {
		if !strings.Contains(help, want) {
			t.Errorf("root help never mentions %q", want)
		}
	}
}

func TestWrongArgumentCountIsRejectedBeforeAnyRequest(t *testing.T) {
	cases := [][]string{
		{"restart"},                       // needs a component
		{"delete-recipe", "com.acme.api"}, // needs a version too
		{"status", "extra"},               // takes none
	}
	for _, args := range cases {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			root := NewRootCommand()
			root.SetOut(&bytes.Buffer{})
			root.SetErr(&bytes.Buffer{})
			root.SetArgs(args)
			if err := root.Execute(); err == nil {
				t.Error("expected an argument error")
			}
		})
	}
}

func TestAddrFallsBackToTheEnvironmentButTheFlagWins(t *testing.T) {
	cases := []struct {
		name string
		env  string
		args []string
		want string
	}{
		{"default when nothing is set", "", nil, "http://127.0.0.1:8080"},
		{"environment when the flag is absent", "http://127.0.0.1:9180", nil, "http://127.0.0.1:9180"},
		{"flag beats the environment", "http://127.0.0.1:9180", []string{"--addr", "http://10.0.0.1:8080"}, "http://10.0.0.1:8080"},
		{"trailing slash is trimmed", "http://127.0.0.1:9180/", nil, "http://127.0.0.1:9180"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Setenv("KEYSTONE_ADDR", tc.env)
			agentAddr, apiToken, sshDest = "", "", ""

			root := NewRootCommand()
			var got string
			probe := &cobra.Command{
				Use:     "probe",
				GroupID: groupLocal,
				RunE: func(*cobra.Command, []string) error {
					got = agentAddr
					return nil
				},
			}
			root.AddCommand(probe)
			root.SetOut(&bytes.Buffer{})
			root.SetErr(&bytes.Buffer{})
			root.SetArgs(append(tc.args, "probe"))

			if err := root.Execute(); err != nil {
				t.Fatal(err)
			}
			if got != tc.want {
				t.Errorf("addr = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestComponentPathEscapesTheName(t *testing.T) {
	// The action separator must survive escaping, or the agent cannot tell a
	// stop from a restart.
	if got := componentPath("api", "restart"); got != "/v1/components/api:restart" {
		t.Errorf("componentPath = %q", got)
	}
	if got := componentPath("web api", "stop"); got != "/v1/components/web%20api:stop" {
		t.Errorf("componentPath = %q, want the space escaped", got)
	}
	if got := componentPath("/api/", "stop"); got != "/v1/components/api:stop" {
		t.Errorf("componentPath = %q, want surrounding slashes trimmed", got)
	}
	if got := componentPath("a?b#c", "stop"); strings.ContainsAny(strings.TrimPrefix(got, "/v1/components/"), "?#") {
		t.Errorf("componentPath = %q, want query and fragment characters escaped", got)
	}
}

func TestFormatBody(t *testing.T) {
	cases := []struct {
		name    string
		payload string
		want    string
	}{
		{"no content means OK", "", "OK"},
		{"whitespace only means OK", "\n  \n", "OK"},
		{"json is indented", `{"startOrder":["db"]}`, "{\n  \"startOrder\": [\n    \"db\"\n  ]\n}"},
		{"plain text passes through", "not json at all", "not json at all"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := formatBody([]byte(tc.payload)); got != tc.want {
				t.Errorf("formatBody(%q) = %q, want %q", tc.payload, got, tc.want)
			}
		})
	}
}

func TestParseSSHTarget(t *testing.T) {
	cases := []struct {
		dest     string
		wantHost string
		wantPort string
	}{
		{"edge-001", "edge-001", ""},
		{"ops@edge-001", "ops@edge-001", ""},
		{"edge-001:52022", "edge-001", "52022"},
		{"ops@edge-001:2222", "ops@edge-001", "2222"},
		{"192.0.2.10:22", "192.0.2.10", "22"},
		{"[2001:db8::1]:2222", "[2001:db8::1]", "2222"},
		{"[fd7a:115c::1]", "[fd7a:115c::1]", ""},
		{"ops@[2001:db8::1]", "ops@[2001:db8::1]", ""},
		// A bare IPv6 address has colons of its own; none of them is a port.
		{"2001:db8::1", "2001:db8::1", ""},
		{"fd7a:115c:a1e0::1", "fd7a:115c:a1e0::1", ""},
		// A ~/.ssh/config Host alias is passed through untouched.
		{"edge-lab", "edge-lab", ""},
	}
	for _, tc := range cases {
		t.Run(tc.dest, func(t *testing.T) {
			got, err := parseSSHTarget(tc.dest)
			if err != nil {
				t.Fatalf("parseSSHTarget(%q): %v", tc.dest, err)
			}
			if got.Host != tc.wantHost || got.Port != tc.wantPort {
				t.Errorf("= %+v, want host %q port %q", got, tc.wantHost, tc.wantPort)
			}
		})
	}
}

func TestParseSSHTargetRejectsBadDestinations(t *testing.T) {
	// A destination starting with a dash would be read by ssh as an option.
	for _, dest := range []string{"", "   ", "-oProxyCommand=touch /tmp/pwned", "@host:22:23", "[::1", "@edge-001"} {
		if _, err := parseSSHTarget(dest); err == nil {
			t.Errorf("parseSSHTarget(%q) accepted an invalid destination", dest)
		}
	}
}

func TestSSHCommandForwardsStdioToTheAgent(t *testing.T) {
	cmd := sshCommand(sshTarget{Host: "ops@edge-001", Port: "2222"}, "127.0.0.1:8080")
	got := strings.Join(cmd.Args, " ")
	want := "ssh -o LogLevel=ERROR -p 2222 ops@edge-001 -W 127.0.0.1:8080"
	if got != want {
		t.Errorf("ssh args = %q, want %q", got, want)
	}

	cmd = sshCommand(sshTarget{Host: "edge-001"}, "127.0.0.1:8080")
	if strings.Contains(strings.Join(cmd.Args, " "), "-p") {
		t.Error("no port was given, so ssh should not be passed -p")
	}
}
