// Command openapi-gen writes the OpenAPI document for Keystone's HTTP control
// plane, derived from the route table the router itself is built from.
//
// The point is that the spec cannot drift. Paths, methods and parameters come
// from internal/adapter/http.DocumentedRoutes(), and response schemas are
// reflected from the very Go types the handlers encode — so renaming a field in
// adapter.PlanStatus changes the generated spec, and CI fails if the checked-in
// spec was not regenerated.
//
// Usage:
//
//	go run ./cmd/openapi-gen -o site/content/reference/api/openapi.yaml
//	go run ./cmd/openapi-gen -check          # fail if the file is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	ksHTTP "github.com/carlosprados/keystone/internal/adapter/http"
	"github.com/carlosprados/keystone/internal/version"
	"github.com/swaggest/openapi-go"
	"github.com/swaggest/openapi-go/openapi31"
)

const defaultOut = "site/content/reference/api/openapi.yaml"

func main() {
	out := flag.String("o", defaultOut, "output path for the OpenAPI document")
	check := flag.Bool("check", false, "exit non-zero if the file on disk differs from what would be generated")
	flag.Parse()

	doc, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "openapi-gen: %v\n", err)
		os.Exit(1)
	}

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "openapi-gen: cannot read %s: %v\n", *out, err)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(existing), bytes.TrimSpace(doc)) {
			fmt.Fprintf(os.Stderr, "openapi-gen: %s is out of date; run `task openapi`\n", *out)
			os.Exit(1)
		}
		fmt.Printf("openapi-gen: %s is up to date\n", *out)
		return
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "openapi-gen: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, doc, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "openapi-gen: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("openapi-gen: wrote %s\n", *out)
}

func generate() ([]byte, error) {
	r := openapi31.NewReflector()
	spec := r.SpecEns()

	spec.Info.
		WithTitle("Keystone agent API").
		WithVersion(specVersion()).
		WithDescription(strings.TrimSpace(`
The local control plane of a Keystone agent: apply a deployment plan, inspect what
is actually running, and control individual components.

This document is generated from the agent's route table, so it describes the
endpoints the running binary serves rather than a hand-maintained copy of them.

Authentication: every endpoint except /healthz requires ` + "`Authorization: Bearer <token>`" + `
when the agent was started with a token. A token is mandatory for the agent to
bind any address other than loopback, so in practice a reachable API is always
authenticated. Keystone does not terminate TLS — put it behind a reverse proxy or
reach it over a VPN.
`))

	spec.WithServers(
		openapi31.Server{URL: "http://127.0.0.1:8080", Description: strPtr("Default loopback bind")},
		openapi31.Server{URL: "https://{device}", Description: strPtr("A device behind a TLS-terminating proxy"),
			Variables: map[string]openapi31.ServerVariable{
				"device": {Default: "device.example.com"},
			}},
	)

	spec.ComponentsEns().WithSecuritySchemesItem("bearerAuth", openapi31.SecuritySchemeOrReference{
		SecurityScheme: &openapi31.SecurityScheme{
			HTTPBearer:  &openapi31.SecuritySchemeHTTPBearer{Scheme: "bearer"},
			Description: strPtr("The value of KEYSTONE_API_TOKEN on the agent."),
		},
	})

	for _, route := range ksHTTP.DocumentedRoutes() {
		for _, method := range route.Methods {
			if err := addOperation(r, route, method); err != nil {
				return nil, fmt.Errorf("%s %s: %w", method, route.Path, err)
			}
		}
	}

	y, err := r.Spec.MarshalYAML()
	if err != nil {
		return nil, err
	}
	header := "# Generated by cmd/openapi-gen from the agent's route table. Do not edit by hand:\n" +
		"# run `task openapi` after changing internal/adapter/http/routes.go or any response type.\n"
	return append([]byte(header), y...), nil
}

func addOperation(r *openapi31.Reflector, route ksHTTP.Route, method string) error {
	oc, err := r.NewOperationContext(method, route.Path)
	if err != nil {
		return err
	}
	oc.SetSummary(route.Summary)
	if route.Description != "" {
		oc.SetDescription(route.Description)
	}
	oc.SetTags(tagFor(route.Path))
	oc.SetID(operationID(method, route.Path))

	// Parameters: synthesised into a struct with the tags the reflector expects, so
	// it generates and validates them itself rather than us patching the document
	// afterwards. This is what makes a path placeholder impossible to forget.
	if params := paramsStruct(route.Params); params != nil {
		oc.AddReqStructure(params)
	}

	// Request body.
	switch {
	case route.RawTOML && method == http.MethodPost:
		oc.AddReqStructure(new(string), func(cu *openapi.ContentUnit) {
			cu.ContentType = "text/plain"
			cu.Description = "TOML document"
		})
	case route.Request != nil:
		oc.AddReqStructure(route.Request)
	}

	// Success response.
	status := route.SuccessStatus
	if status == 0 {
		status = http.StatusOK
	}
	switch {
	case route.PlainText:
		oc.AddRespStructure(new(string), func(cu *openapi.ContentUnit) {
			cu.HTTPStatus = status
			cu.ContentType = "text/plain"
		})
	case route.Response != nil && method != http.MethodPost || (route.Response != nil && status == http.StatusOK):
		oc.AddRespStructure(route.Response, func(cu *openapi.ContentUnit) {
			cu.HTTPStatus = status
		})
	default:
		oc.AddRespStructure(nil, func(cu *openapi.ContentUnit) {
			cu.HTTPStatus = status
			cu.Description = statusText(status)
		})
	}

	// Every authenticated endpoint can answer 401: the token is compared in
	// constant time and a mismatch is not negotiable.
	errors := route.Errors
	if !route.NoAuth {
		errors = append(errors, http.StatusUnauthorized)
	}

	// Documented failures: the agent answers errors as plain text, not JSON.
	for _, code := range errors {
		oc.AddRespStructure(new(string), func(cu *openapi.ContentUnit) {
			cu.HTTPStatus = code
			cu.ContentType = "text/plain"
			cu.Description = statusText(code)
		})
	}

	if err := r.AddOperation(oc); err != nil {
		return err
	}

	// Security and parameters go straight onto the operation: the reflector's
	// struct-based path is more machinery than this table needs.
	return decorate(r, route, method)
}

// paramsStruct builds a struct type whose fields carry the `path:` and `query:`
// tags openapi-go reads, one field per documented parameter, and returns a zero
// value of it. Returns nil when the route has no parameters.
func paramsStruct(params []ksHTTP.Param) interface{} {
	if len(params) == 0 {
		return nil
	}
	fields := make([]reflect.StructField, 0, len(params))
	for _, p := range params {
		tag := fmt.Sprintf(`%s:"%s" description:"%s"`, p.In, p.Name, strings.ReplaceAll(p.Description, `"`, "'"))
		if p.Required {
			tag += ` required:"true"`
		}
		if p.Example != "" {
			tag += fmt.Sprintf(` example:"%s"`, p.Example)
		}
		fields = append(fields, reflect.StructField{
			Name: exportedName(p.Name),
			Type: reflect.TypeOf(""),
			Tag:  reflect.StructTag(tag),
		})
	}
	return reflect.New(reflect.StructOf(fields)).Elem().Interface()
}

// exportedName turns a parameter name into a valid exported Go field name.
func exportedName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' || r == '.' })
	out := ""
	for _, p := range parts {
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	return out
}

// decorate adds the security requirement to an operation that has already been
// registered. Parameters are handled by the reflector, from paramsStruct.
func decorate(r *openapi31.Reflector, route ksHTTP.Route, method string) error {
	pathItem, ok := r.Spec.Paths.MapOfPathItemValues[route.Path]
	if !ok {
		return fmt.Errorf("path %s missing after registration", route.Path)
	}
	op := operationFor(&pathItem, method)
	if op == nil {
		return fmt.Errorf("operation %s %s missing after registration", method, route.Path)
	}

	if !route.NoAuth {
		op.Security = []map[string][]string{{"bearerAuth": {}}}
	}

	setOperation(&pathItem, method, op)
	r.Spec.Paths.MapOfPathItemValues[route.Path] = pathItem
	return nil
}

func operationFor(pi *openapi31.PathItem, method string) *openapi31.Operation {
	switch method {
	case http.MethodGet:
		return pi.Get
	case http.MethodPost:
		return pi.Post
	case http.MethodDelete:
		return pi.Delete
	case http.MethodPut:
		return pi.Put
	}
	return nil
}

func setOperation(pi *openapi31.PathItem, method string, op *openapi31.Operation) {
	switch method {
	case http.MethodGet:
		pi.Get = op
	case http.MethodPost:
		pi.Post = op
	case http.MethodDelete:
		pi.Delete = op
	case http.MethodPut:
		pi.Put = op
	}
}

func tagFor(path string) string {
	switch {
	case strings.HasPrefix(path, "/v1/plan"):
		return "plan"
	case strings.HasPrefix(path, "/v1/components"):
		return "components"
	case strings.HasPrefix(path, "/v1/recipes"):
		return "recipes"
	default:
		return "agent"
	}
}

// operationID turns "POST /v1/components/{name}:restart" into
// "postComponentsNameRestart", which is what client generators use for method
// names.
func operationID(method, path string) string {
	clean := strings.NewReplacer("/", " ", "{", " ", "}", " ", ":", " ", "-", " ", ".", " ").Replace(path)
	parts := strings.Fields(clean)
	id := strings.ToLower(method)
	for _, p := range parts {
		if p == "v1" {
			continue
		}
		id += strings.ToUpper(p[:1]) + p[1:]
	}
	return id
}

func statusText(code int) string {
	if t := http.StatusText(code); t != "" {
		return t
	}
	return fmt.Sprintf("status %d", code)
}

func specVersion() string {
	if v := version.Version; v != "" && v != "dev" {
		return strings.TrimPrefix(v, "v")
	}
	return "0.0.0-dev"
}

func strPtr(s string) *string { return &s }
