// Command cli-gen writes the published command-line reference, derived from the
// definitions the binaries themselves run on.
//
// The point is the same as cmd/openapi-gen: the page cannot drift. keystonectl's
// commands, flags and examples are walked from the Cobra tree in internal/cli,
// and the agent's flags come from running its own -help. A command added without
// regenerating this page makes CI fail.
//
// The page was previously written by hand, and it showed: it shipped with the
// help output of a binary built in a scratch directory, publishing a stranger's
// temporary path as the agent's usage line.
//
// It writes two pages: the agent's flags, and keystonectl's own reference.
//
// Usage:
//
//	go run ./cmd/cli-gen -dir site/content/reference
//	go run ./cmd/cli-gen -check          # fail if either page is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/carlosprados/keystone/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const defaultDir = "site/content/reference"

func main() {
	dir := flag.String("dir", defaultDir, "directory holding the generated reference pages")
	check := flag.Bool("check", false, "exit non-zero if the files on disk differ from what would be generated")
	flag.Parse()

	pages, err := generate()
	if err != nil {
		fmt.Fprintf(os.Stderr, "cli-gen: %v\n", err)
		os.Exit(1)
	}

	for _, name := range sortedNames(pages) {
		path := filepath.Join(*dir, name)
		body := pages[name]

		if *check {
			existing, err := os.ReadFile(path)
			if err != nil {
				fmt.Fprintf(os.Stderr, "cli-gen: cannot read %s: %v\n", path, err)
				os.Exit(1)
			}
			if !bytes.Equal(bytes.TrimSpace(existing), bytes.TrimSpace(body)) {
				fmt.Fprintf(os.Stderr, "cli-gen: %s is out of date; run `task cli-docs`\n", path)
				os.Exit(1)
			}
			fmt.Printf("cli-gen: %s is up to date\n", path)
			continue
		}

		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "cli-gen: %v\n", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, body, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "cli-gen: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("cli-gen: wrote %s\n", path)
	}
}

func sortedNames(pages map[string][]byte) []string {
	names := make([]string, 0, len(pages))
	for name := range pages {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// generate builds one page per binary. keystonectl gets its own, so it appears
// in the site navigation rather than being buried halfway down the agent's flag
// reference.
func generate() (map[string][]byte, error) {
	agentHelp, err := agentUsage()
	if err != nil {
		return nil, err
	}

	var agent strings.Builder
	agent.WriteString(agentFrontMatter)
	agent.WriteString(generatedNotice)
	agent.WriteString(agentSection(agentHelp))
	agent.WriteString(tailSection)

	var ctl strings.Builder
	ctl.WriteString(ctlFrontMatter)
	ctl.WriteString(generatedNotice)
	ctl.WriteString(keystonectlSection())

	return map[string][]byte{
		"cli.md":         []byte(agent.String()),
		"keystonectl.md": []byte(ctl.String()),
	}, nil
}

const agentFrontMatter = `+++
title = "Agent flags"
weight = 71
description = "Every flag the keystone agent accepts."
+++

`

const ctlFrontMatter = `+++
title = "keystonectl"
weight = 72
description = "The command-line client: every command, its flags, and how to reach an agent over SSH."
+++

`

const generatedNotice = `<!-- Generated by cmd/cli-gen from the agent's flag set and keystonectl's command
     tree. Do not edit by hand: run ` + "`task cli-docs`" + ` after changing either. -->

`

// agentUsage builds the agent and reads its own -help output, so the documented
// flags are the ones the binary actually accepts.
func agentUsage() (string, error) {
	dir, err := os.MkdirTemp("", "cli-gen")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(dir)

	bin := filepath.Join(dir, "keystone")
	build := exec.Command("go", "build", "-o", bin, "./cmd/keystone")
	if out, err := build.CombinedOutput(); err != nil {
		return "", fmt.Errorf("building the agent: %w\n%s", err, out)
	}

	// -help exits non-zero by convention in the flag package; the output is
	// what matters.
	help, _ := exec.Command(bin, "-help").CombinedOutput()

	// The usage line names the binary by path, which would publish whatever
	// temporary directory this ran in.
	usage := regexp.MustCompile(`(?m)^Usage of .*:$`)
	return usage.ReplaceAllString(strings.TrimSpace(string(help)), "Usage of keystone:"), nil
}

func agentSection(help string) string {
	return "The authoritative list is always `keystone --help` on the binary you are\nrunning. This is that output:\n\n```text\n" +
		help + "\n```\n\n" + agentProse
}

const agentProse = `### The ones you will actually use

| Flag | Why |
|---|---|
| ` + "`--http`" + ` | Listen address. ` + "`\"\"`" + ` disables the HTTP adapter entirely |
| ` + "`--api-token`" + ` | Required to bind anything but loopback |
| ` + "`--insecure-skip-verify`" + ` | Development only. Disables mandatory artifact integrity |
| ` + "`--nats-url`" + ` / ` + "`--nats-device-id`" + ` | Enable the NATS adapter |
| ` + "`--mqtt-broker`" + ` / ` + "`--mqtt-device-id`" + ` | Enable the MQTT adapter |
| ` + "`--demo`" + ` | Run a built-in mock 3-component stack. Good for a first look |
| ` + "`--version`" + ` | Print version and commit |

Flags always win over the equivalent environment variable.

`

// keystonectlSection walks the real command tree, so a new command appears here
// the moment it is added.
func keystonectlSection() string {
	root := cli.NewRootCommand()

	var b strings.Builder
	b.WriteString(ctlIntro)

	b.WriteString("### The commands\n\n")
	for _, group := range root.Groups() {
		var rows []string
		for _, cmd := range root.Commands() {
			if cmd.GroupID != group.ID || !cmd.IsAvailableCommand() {
				continue
			}
			rows = append(rows, fmt.Sprintf("| `%s` | %s |\n", cmd.Use, cmd.Short))
		}
		if len(rows) == 0 {
			continue
		}
		b.WriteString("**" + strings.TrimSuffix(group.Title, ":") + "**\n\n")
		b.WriteString("| Command | What it does |\n|---|---|\n")
		for _, row := range rows {
			b.WriteString(row)
		}
		b.WriteString("\n")
	}

	b.WriteString(ctlFlags(root))
	b.WriteString(ctlOutro)
	return b.String()
}

const ctlIntro = `**The CLI documents itself, and that is the authoritative reference.** Every
command carries a description, runnable examples and the endpoint it calls, so
the fastest way to learn it is to ask it:

` + "```bash" + `
keystonectl help              # every command, grouped
keystonectl help restart      # one command, with examples
keystonectl restart --help    # the same
` + "```" + `

` + "`keystonectl help <command>`" + ` prints, among other things, the line
` + "`Calls POST /v1/components/{name}:restart.`" + ` — the mapping from CLI to API is
in the tool, not only on this page.

Shell completion comes with it:

` + "```bash" + `
source <(keystonectl completion bash)   # or zsh, fish, powershell
` + "```" + `

`

func ctlFlags(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("### Global flags\n\nThese apply to every command.\n\n")
	b.WriteString("| Flag | What it is | Default |\n|---|---|---|\n")
	root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		def := f.DefValue
		if def == "" {
			def = "(none)"
		} else {
			def = "`" + def + "`"
		}
		b.WriteString(fmt.Sprintf("| `--%s` | %s | %s |\n", f.Name, f.Usage, def))
	})
	b.WriteString("\nA flag always wins over its environment variable, which wins over the default.\n\n")
	return b.String()
}

const ctlOutro = `` +
	"`--addr` is worth exporting when the agent does not use the default port:\n\n" +
	"```bash\nexport KEYSTONE_ADDR=http://127.0.0.1:9180\nkeystonectl components\n```\n\n" +
	"`restart` takes `--wait pid|health` and `--timeout`, so a script can block\nuntil the component is actually serving:\n\n" +
	"```bash\nkeystonectl restart api --wait health --timeout 120s\n```\n\n" +
	`### Exit codes

| Code | Meaning |
|---|---|
| ` + "`0`" + ` | The request succeeded |
| ` + "`1`" + ` | The agent or the network reported a failure |
| ` + "`2`" + ` | The command was used wrongly — bad arguments, bad ` + "`--ssh`" + ` destination |

Note ` + "`stop-plan`" + ` (everything) versus ` + "`stop <component>`" + ` (one thing) — they
are different commands, and the plural mistake is an outage.

Every command prints the agent's own response. A dry run reports the order it
would use, not a bare ` + "`OK`" + `:

` + "```console" + `
$ keystonectl restart-dry api
{
  "startOrder": [
    "api"
  ],
  "stopOrder": null
}
` + "```" + `

### Reaching an agent bound to loopback

The agent listens on ` + "`127.0.0.1`" + ` by default, and binding anything else
[requires a token](../../security/api-auth/). On a real device that means its API
is only reachable from the device itself.

` + "`--ssh`" + ` carries the request there, so there is no ` + "`ssh -L`" + ` to keep alive in
another terminal and no port to expose:

` + "```bash" + `
keystonectl --ssh ops@edge-001 components
keystonectl --ssh ops@edge-001:52022 --addr http://127.0.0.1:9180 restart-dry api
` + "```" + `

**` + "`--addr`" + ` is resolved on the far side.** The default ` + "`http://127.0.0.1:8080`" + ` is
therefore the *agent's* loopback — exactly the interface it is bound to. Both
variables can be exported together for a device you work on often:

` + "```bash" + `
export KEYSTONE_SSH=ops@edge-001:52022
export KEYSTONE_ADDR=http://127.0.0.1:9180
keystonectl status
` + "```" + `

What it does under the hood is run your own ` + "`ssh`" + ` client with ` + "`-W`" + `, which splices
its stdio to a host and port on the far side. That is deliberate: it inherits
your ` + "`~/.ssh/config`" + ` — ` + "`Host`" + ` aliases, ` + "`IdentityFile`" + `, ` + "`ProxyJump`" + ` through a
bastion, the agent, certificates and ` + "`known_hosts`" + ` — and the host key is verified
by ` + "`ssh`" + ` under your own rules. Keystone adds no cryptography of its own here.

The consequences are worth knowing:

- It needs the ` + "`ssh`" + ` binary on **your** machine (the device only needs ` + "`sshd`" + `).
- The device's ` + "`sshd`" + ` must allow ` + "`AllowTcpForwarding`" + `, which is the default but
  is sometimes turned off on a hardened image. If it is off, ` + "`-W`" + ` fails.
- SSH errors — unknown host, rejected key — reach you verbatim on stderr rather
  than as an opaque connection failure.
- ` + "`--ssh`" + ` is Unix-only. On Windows the rest of the CLI works; forward the port
  with ` + "`ssh -L`" + ` and point ` + "`--addr`" + ` at it.

`

const tailSection = `## keystoneserver

A minimal static file server, for serving test artifacts during development:

` + "```bash" + `
keystoneserver --addr :9000 --root ./dist
` + "```" + `

## Task targets

Development uses [Task](https://taskfile.dev/), not make:

` + "```bash" + `
task build     # all three binaries, with version ldflags
task run       # agent with HTTP on :8080
task dev       # live reload via air
task test      # go test -v ./...
task fmt       # go fmt ./...
task vet       # go vet ./...
task hooks     # install the go fmt pre-commit hook
task openapi   # regenerate the OpenAPI document
task cli-docs  # regenerate this page
` + "```" + `
`
